name: ci
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  commitlint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v5
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Check NCBI secrets
        env:
          secret_email: ${{ secrets.NCBI_EMAIL }}
          secret_api_key: ${{ secrets.NCBI_API_KEY }}
        if: ${{ env.secret_email == '' || env.secret_api_key == '' }}
        run: |
          echo "NCBI authentication secret missing. Exiting."
          exit 1
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore pytest cache
        id: cache-pytest-restore
        uses: actions/cache/restore@v4
        with:
          path: .pytest_cache
          key: saved-pytest
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          installer-parallel: true
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install packages
        run: poetry install
      - name: Test
        run: poetry run pytest
      - name: Save pytest cache
        id: cache-pytest-save
        uses: actions/cache/save@v4
        with:
          path: .pytest_cache
          key: ${{ steps.cache-pytest-restore.outputs.cache-primary-key}}

  release:
    if: github.event_name == 'push'
    needs:
      - commitlint
      - test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install semantic-release
        run: npm i semantic-release@v23.0.0 conventional-changelog-conventionalcommits@7.0.2
      - name: Release
        env:
          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release