name: publish

on:
  release:
    types: [published]

jobs:
  pypi:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          installer-parallel: true
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Version
        run: poetry version ${{ github.event.release.tag_name }}
      - name: Build
        run: poetry build
      - name: Publish
        run: poetry publish -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_TOKEN }}
